### PR TITLE
Update Article page example

### PR DESCRIPTION
**Pull request by alexwybraniec**

### CODE REVIEW

**Comment by alexwybraniec** [comment]
Not going to merge until review with @chrisdevereux has taken place.

**Comment by chrisdevereux** [comment]
one thing I've spotted in the backports branch is that we've added a 'prose' class, which applies some changes to margins and padding. we probably want that applied in our article pattern too

**Comment by chrisdevereux** [comment]
`<ul>` should have `govuk-list govuk-list--bullet` class applied

**Comment by chrisdevereux** [comment]
otherwise looks good

**Comment by alexwybraniec** [comment]
Agreed that additional classes that need to be added to ULs, will be scoped by the lbcamden-prose class, as we believe that we will not have the ability to add classes to content created in a rich text editor.

**Pull request merged**
